### ISSUE TITLE
Debugging SimpleMVVMToolkit.Express

### ISSUE THREAD

**Issue by brianke** [SimpleMvvm/SimpleMvvmToolkit.Express#1]
I am trying to debug an issue where an observable collection is getting the items within it duplicated on BeginEdit().  I have downloaded the source code and added the SimpleMVVMToolkit.Express to my existing solution.  However, when I try to build the SimpleMVVMToolkit.Express project I get the following error message:

> Cannot infer TargetFrameworkIdentifier and/or TargetFrameworkVersion from TargetFramework='uap10.0'. They must be specified explicitly.

I cannot find a solution to this via Google search.  I am using VS 2017 15.3.2.  Do I need to add one of the components for VS or is there something else that needs added?

**Comment by tonysneed** [comment]
I think we will need to update the project to .NET Standard 2.0 for it to work with UAP. I’ll give it a try.

**Comment by brianke** [comment]
OK, in case it matters, I do not need UAP, I am only using .Net 4.6.

**Comment by tonysneed** [comment]
No problem .. I think it still may be resolved by updating to the current SDK. I’ll give it a try.

**Comment by tonysneed** [comment]
I upgraded the project to .NET Standard 2.0 with csproj instead of project.json.  So everything builds fine now if you get latest.  I also published the v2.0.0-beta package to NuGet: <https://www.nuget.org/packages/SimpleMvvmToolkit.Express/2.0.0-beta>

**Comment by brianke** [comment]
Thanks for the quick turn around!  I am having another issue now and getting the following error:

> The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.	

This is my first try at downloading a project from GitHub so please let me know if I am missing a step.  Here is what I have done so far:

1. Download ZIP file of project from GitHub
2. Navigate to ..\SimpleMvvmToolkit.Express-master.zip\SimpleMvvmToolkit.Express-master\Src and extract contents to local drive
3. Open SimpleMvvmToolkit.Express.sln using Visual Studio 2017 (ver. 15.3.2).
4. Rebuild solution, which results in error above.

I noticed that in VS I have some depenencies that are not being found:
![image](https://user-images.githubusercontent.com/925682/32111720-4efcdf2c-bb09-11e7-9b66-c72a70571ddb.png)

I tried to add the NewtonSoft.Json NuGet package to the SimpleMVVMToolkit.Express project, and it appeared to install, but the yellow exclamation points are still present and a rebuild results in the same error as above.

**Comment by tonysneed** [comment]
So you need to install the .NET Core 2.0 SDK: https://www.microsoft.com/net/download/core.

**Comment by brianke** [comment]
Thank you, that did the trick.

**Comment by tonysneed** [comment]
Great!
